#!/bin/sh

mysqld_safe &

service rabbitmq-server start

/usr/local/bin/wrapdocker 

mkdir /var/run/screen
chmod 775 /var/run/screen

if [ -n "$STABLE_RELEASE" ]; then
    # Sets the branch for each project, if tagging a stable release.
    # This regex sanitizes our input...
    STABLE_RELEASE=${STABLE_RELEASE//[^a-zA-Z0-9_]/}
    sed -n "/_BRANCH=/{ s/=.*/=stable\/${STABLE_RELEASE}/g; p; }" /devstack/stackrc >> /devstack/localrc.d/001-stable-branch

    cd /devstack
    git checkout stable/${STABLE_RELEASE}
fi

# Git repos
echo <<EOF >>/devstack/localrc.d/005-nova-git
# Base GIT Repo URL
# Another option is http://review.openstack.org/p
GIT_BASE=${GIT_BASE:-git://git.openstack.org}
# compute service
NOVA_REPO=${NOVA_REPO:-${GIT_BASE}/openstack/nova.git}
NOVA_BRANCH=${NOVA_BRANCH:-master}
EOF

su devstack -c '/devstack/tools/docker/install_docker.sh'
su devstack -c '/devstack/stack.sh'
