#!/bin/sh

mysqld_safe &

service rabbitmq-server start

/usr/local/bin/wrapdocker 

mkdir /var/run/screen
chmod 777 /var/run/screen

su devstack -c '/devstack/tools/docker/install_docker.sh'
su devstack -c '/devstack/stack.sh'

bash 

#tail -f /opt/stack/logs/*
