#!/bin/sh

mysqld_safe &

service rabbitmq-server start

/usr/local/bin/wrapdocker 

mkdir /var/run/screen
chmod 777 /var/run/screen

# extracted from devstack-vm-gate.sh
echo <<EOF >>/devstack/localrc
ACTIVE_TIMEOUT=90
BOOT_TIMEOUT=90
ASSOCIATE_TIMEOUT=60
TERMINATE_TIMEOUT=60
SWIFT_HASH=1234123412341234
ROOTSLEEP=0
ERROR_ON_CLONE=True
SERVICE_HOST=127.0.0.1
# Screen console logs will capture service logs.
SYSLOG=False
VERBOSE=True
FIXED_RANGE=10.1.0.0/24
FIXED_NETWORK_SIZE=256
SWIFT_REPLICAS=1
LOG_COLOR=False
PIP_USE_MIRRORS=False
USE_GET_PIP=1
# Don't reset the requirements.txt files after g-r updates
UNDO_REQUIREMENTS=False
CINDER_PERIODIC_INTERVAL=10
export OS_NO_CACHE=True
EOF

su devstack -c '/devstack/tools/docker/install_docker.sh'
su devstack -c '/devstack/stack.sh'

su devstack -c '/opt/stack/tempest/run_tempest.sh -N -s'

#tail -f /opt/stack/logs/*
