#!/bin/bash
# Embarrassingly bad shell scripting below (because one 'eval' isn't enough!)
cd /devstack
. functions
. stackrc
cat <(echo ". functions; . stackrc") <(for project in $(declare | sed -n '/_REPO=/{ s/^\(.*\)_REPO=.*/\1/; p; }'); do eval "echo git_clone \$${project}_REPO $(git grep -h ${project}_DIR= | sed 's/.*=//') \$${project}_BRANCH";  done | grep git.openstack.org) | bash
